[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'source ~/.config/nvim/rc/defx.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/rc/denite.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = 'source ~/.config/nvim/rc/neosnippet.vim'

[[plugins]]
repo = "Shougo/neocomplcache.vim"

[[plugins]]
repo = "Shougo/neocomplcache-rsense.vim"
