[[plugins]]
repo = "fatih/vim-go"
hook_add = '''
  so ~/.vim/rc/vim-go.vim
'''

[[plugins]]
repo =  "tomlion/vim-solidity"

[[plugins]]
repo = "mattn/emmet-vim"

[[plugins]]
repo = "mattn/webapi-vim"

[[plugins]]
repo = "kana/vim-textobj-user"

[[plugins]]
repo = "rhysd/vim-textobj-ruby"

[[plugins]]
repo = "chrisbra/csv.vim"

[[plugins]]
repo = "slim-template/vim-slim"

[[plugins]]
repo = "hashivim/vim-terraform"

[[plugins]]
repo = "juliosueiras/vim-terraform-completion"

[[plugins]]
repo = "elzr/vim-json"

[[plugins]]
repo = "leafgarland/typescript-vim"

[[plugins]]
repo = "fuenor/JpFormat.vim"

[[plugins]]
repo = "uarun/vim-protobuf"

[[plugins]]
repo = "rhysd/vim-clang-format"
hook_add = '''
  autocmd FileType proto ClangFormatAutoEnable
'''

[[plugins]]
repo = "peitalin/vim-jsx-typescript"
hook_add = '''
  " dark red
  hi tsxTagName guifg=#E06C75
  hi tsxComponentName guifg=#E06C75
  hi tsxCloseComponentName guifg=#E06C75

  " orange
  hi tsxCloseString guifg=#F99575
  hi tsxCloseTag guifg=#F99575
  hi tsxCloseTagName guifg=#F99575
  hi tsxAttributeBraces guifg=#F99575
  hi tsxEqual guifg=#F99575

  " yellow
  hi tsxAttrib guifg=#F8BD7F cterm=italic
'''

[[plugins]]
repo = "posva/vim-vue"

[[plugins]]
repo = "towolf/vim-helm"

[[plugins]]
repo = "pocke/rbs.vim"
