[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'
hook_add = 'source ~/.config/nvim/rc/LanguageClient-neovim.rc.vim'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.config/nvim/rc/vim-go.rc.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/.config/nvim/rc/rust.vim.rc.vim'

[[plugins]]
repo = 'rust-lang/rustfmt'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_add = 'source ~/.config/nvim/rc/vim-racer.rc.vim'

[[plugins]]
repo =  'tomlion/vim-solidity'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'
