[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.config/nvim/rc/vim-go.vim'

[[plugins]]
repo = 'sebdah/vim-delve'
hook_add = 'source ~/.config/nvim/rc/vim-delve.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/.config/nvim/rc/rust.vim.vim'

[[plugins]]
repo = 'rust-lang/rustfmt'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_add = 'source ~/.config/nvim/rc/vim-racer.vim'

[[plugins]]
repo =  'tomlion/vim-solidity'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

# [[plugins]]
# repo = 'ruby-formatter/rufo-vim'
# hook_add = 'source ~/.config/nvim/rc/rufo-vim.vim'

[[plugins]]
repo = 'chrisbra/csv.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = '["markdown", "pandoc.markdown", "rmd"]'
build = 'sh -c "cd app & yarn install"'
hook_add = 'source ~/.config/nvim/rc/markdown-preview.nvim.vim'

