[[plugins]]
repo = "neoclide/coc.nvim"
hook_add = '''
  so ~/.vim/rc/coc.vim
'''

# [[plugins]]
# repo = "prabirshrestha/vim-lsp"
# hook_add = '''
#   so ~/.vim/rc/vim-lsp.vim
# '''

# [[plugins]]
# repo = "mattn/vim-lsp-settings"

# [[plugins]]
# repo = "SirVer/ultisnips"

# [[plugins]]
# repo = "honza/vim-snippets"

# [[plugins]]
# repo = "prabirshrestha/async.vim"

# [[plugins]]
# repo = "prabirshrestha/asyncomplete.vim"

# [[plugins]]
# repo = "prabirshrestha/asyncomplete-lsp.vim"

# [[plugins]]
# repo = "prabirshrestha/asyncomplete-ultisnips.vim"
