[[plugins]]
repo = "prabirshrestha/vim-lsp"
hook_add = "so ~/.vim/rc/vim-lsp.vim"

[[plugins]]
repo = "mattn/vim-lsp-settings"

[[plugins]]
repo = "Shougo/neosnippet.vim"
hook_add = "so ~/.vim/rc/neosnippet.vim"

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "prabirshrestha/async.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-lsp.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-neosnippet.vim"

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = "thomasfaingnaert/vim-lsp-neosnippet"

[[plugins]]
repo = "honza/vim-snippets"
