[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/rc/fzf.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = "cocopon/vaffle.vim"
hook_add = 'so ~/.config/nvim/rc/vaffle.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/.config/nvim/rc/easymotion.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = 'map <Space>r <Plug>(operator-replace)'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-markdown'
hook_add = 'so ~/.config/nvim/rc/vim-markdown.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'so ~/.config/nvim/rc/indentLine.vim'

[[plugins]]
repo  = 'tpope/vim-obsession'
