[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = "jacoborus/tender.vim"

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.vim/rc/fzf.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/.vim/rc/easymotion.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = 'map <Space>r <Plug>(operator-replace)'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-markdown'
hook_add = 'so ~/.vim/rc/vim-markdown.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'so ~/.vim/rc/indentLine.vim'

[[plugins]]
repo  = 'tpope/vim-obsession'

[[plugins]]
repo = "itchyny/calendar.vim"

[[plugins]]
repo = "skanehira/code2img.vim"

[[plugins]]
repo = 'mattn/vim-molder'
hook_add = 'so ~/.vim/rc/vim-molder.vim'

[[plugins]]
repo = 'mattn/vim-molder-operations'

[[plugins]]
repo = "tpope/vim-speeddating"
[[plugins]]
repo = "jceb/vim-orgmode"
