[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "cohama/lexima.vim"

[[plugins]]
repo = "cespare/vim-toml"

[[plugins]]
repo = "jacoborus/tender.vim"

[[plugins]]
repo = "junegunn/fzf.vim"
hook_add = '''
  nnoremap <silent> <Leader>' :Files <CR>
  nnoremap <silent> <Leader>a :Ag <CR>
  nnoremap <silent> <Leader>b :Buf<CR>
'''

[[plugins]]
repo = "junegunn/fzf"
build = "./install --all"

[[plugins]]
repo = "sebdah/vim-delve"
hook_add = '''
  autocmd FileType go nmap <silent> <leader>d :DlvToggleBreakpoint<CR>
'''

[[plugins]]
repo = "kana/vim-operator-user"

[[plugins]]
repo = "kana/vim-operator-replace"
hook_add = "map <Space>r <Plug>(operator-replace)"

[[plugins]]
repo = "simeji/winresizer"

[[plugins]]
repo = "tpope/vim-endwise"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "tpope/vim-repeat"

[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "tpope/vim-abolish"

[[plugins]]
repo = "tpope/vim-markdown"
hook_add = '''
  let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'ruby', 'javascript']
  let g:markdown_minlines = 100
'''

[[plugins]]
repo = "mattn/vim-sonictemplate"

[[plugins]]
repo = "mattn/emmet-vim"

[[plugins]]
repo = "Yggdroot/indentLine"
hook_add = '''
  let g:indentLine_color_term = 239
  let g:indentLine_concealcursor=""
  let g:indentLine_char_list = ['|', '¦', '┆', '┊']
'''

[[plugins]]
repo  = "tpope/vim-obsession"

[[plugins]]
repo = "itchyny/calendar.vim"

[[plugins]]
repo = "skanehira/code2img.vim"

[[plugins]]
repo = "cocopon/vaffle.vim"
hook_add = 'so ~/.vim/rc/vaffle.vim'

[[plugins]]
repo = "tpope/vim-speeddating"

[[plugins]]
repo = "jceb/vim-orgmode"

[[plugins]]
repo = "ConradIrwin/vim-bracketed-paste"

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo = "svermeulen/vim-macrobatics"
hook_add = '''
  nmap <nowait> q <Plug>(Mac_Play)
  nmap <nowait> gq <Plug>(Mac_RecordNew)
'''


[[plugins]]
repo = "osyo-manga/vim-brightest"
hook_add = '''
  let g:brightest#highlight = {
  \   "group" : "BrightestUnderline"
  \}
  let g:brightest#pattern = '\k\+'
'''

[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = "markonm/traces.vim"

[[plugins]]
repo = "AndrewRadev/switch.vim"

[[plugins]]
repo = "kana/vim-textobj-line"

[[plugins]]
repo = "rhysd/clever-f.vim"

[[plugins]]
repo = "jceb/vim-orgmode"

[[plugins]]
repo = "mattn/calendar-vim"
hook_add = '''
  let g:calendar_diary_extension=".org"
'''

[[plugins]]
repo = "vim-scripts/utl.vim"

[[plugins]]
repo = "tpope/vim-pathogen"

# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = ['context_filetype.vim']

# [[plugins]]
# repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = "inkarkat/vim-SyntaxRange"

[[plugins]]
repo = "junegunn/goyo.vim"

[[plugins]]
repo = "tyru/open-browser.vim"
hook_add = "nmap go <Plug>(openbrowser-smart-search)"
